{
  "compatibilityLevel": 1606,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Allocation\",\"Exposures\",\"Hedges\",\"Rate History\",\"Summary KPIs\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "Hedges_to_Exposures",
        "fromColumn": "Exposure ID",
        "fromTable": "Hedges",
        "toColumn": "ID",
        "toTable": "Exposures"
      },
      {
        "name": "34acc811-31fa-48a7-b0ae-3c78e0cc1dc8",
        "fromColumn": "Value date",
        "fromTable": "Exposures",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_21c2e1c1-fc5e-48e0-b80c-4d6978561abc"
      },
      {
        "name": "b9da0cd2-ffde-4c34-ab84-7e52f2983d1c",
        "fromColumn": "Maturity date",
        "fromTable": "Exposures",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2466a5ef-6e87-4d87-b0cc-2785f10759c5"
      },
      {
        "name": "32ffad15-7bdc-4e4e-b22d-70d99822e5e5",
        "fromColumn": "Maturity date",
        "fromTable": "Hedges",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6ef7637a-e901-41bf-8f5e-395b71cf5eec"
      },
      {
        "name": "765c8a63-69f5-4a20-b2e4-b9847bf594dd",
        "fromColumn": "Captured at",
        "fromTable": "Rate History",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_da8a400a-8ede-4b63-9798-9a361c5655bc"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Allocation",
        "columns": [
          {
            "name": "Currency",
            "dataType": "string",
            "lineageTag": "22f6e114-060d-4b67-bf9a-8ec0593c12ad",
            "sourceColumn": "Currency"
          },
          {
            "name": "Net exposure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "4fcecd45-b5ba-4f96-a50b-72351f488ccc",
            "sourceColumn": "Net exposure"
          },
          {
            "name": "Reserved",
            "dataType": "double",
            "lineageTag": "77b98177-a5dd-4070-9f91-e7dd7d8849dc",
            "sourceColumn": "Reserved"
          },
          {
            "name": "Rate to home",
            "dataType": "double",
            "lineageTag": "04dcef1b-4799-4b20-a6b2-bfb73495fe28",
            "sourceColumn": "Rate to home"
          },
          {
            "name": "Value in home",
            "dataType": "double",
            "lineageTag": "95aff060-12cf-4c57-97b6-3c6b18812c76",
            "sourceColumn": "Value in home"
          },
          {
            "name": "% of portfolio",
            "dataType": "double",
            "lineageTag": "d44c897b-cfb2-4d66-9d39-7510a990c3bc",
            "sourceColumn": "% of portfolio"
          }
        ],
        "lineageTag": "a3cd3c4d-b4d1-47e4-9517-79c7db6e0d9d",
        "measures": [
          {
            "name": "Total Portfolio Value",
            "expression": "SUM ( Allocation[Value in home] )",
            "formatString": "#,0.00",
            "lineageTag": "10740393-6aa9-4324-9681-e13d8bc32c6b"
          },
          {
            "name": "Currencies Held",
            "expression": "COUNTROWS ( Allocation )",
            "formatString": "0",
            "lineageTag": "f720c5b5-c611-4e8c-b234-d8ae123ea145"
          },
          {
            "name": "Largest Currency Weight %",
            "expression": "MAX ( Allocation[% of portfolio] ) / 100",
            "formatString": "0.0%",
            "lineageTag": "7a2c3e2a-659e-4447-b0d1-1072bdf83169"
          },
          {
            "name": "Net Exposure (home)",
            "expression": "SUM ( Allocation[Value in home] )",
            "formatString": "#,0.00",
            "lineageTag": "17019f43-f4cd-4923-977c-c96d4b65206c"
          }
        ],
        "partitions": [
          {
            "name": "Allocation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Projects\\PortfolioProjects\\currency-exchange-platform\\powerbi-exports\\fx-compliant.xlsx\"), null, true),",
                "    Data = Source{[Item=\"Portfolio Summary\", Kind=\"Sheet\"]}[Data],",
                "    NoBlanks = Table.SelectRows(Data, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {null, \"\"}))),",
                "    Skipped = Table.Skip(NoBlanks, 3),",
                "    Promoted = Table.PromoteHeaders(Skipped, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Currency\", type text}, {\"Net exposure\", type number}, {\"Reserved\", type number}, {\"Rate to home\", type number}, {\"Value in home\", type number}, {\"% of portfolio\", type number}})",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Exposures",
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "2fbe6096-287a-4488-81d6-ee27c9cfbc9f",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6a55175-2a94-4137-a4e9-4d9dd8290fdb",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cffe203a-e6a1-40b2-b768-e5adca6047fe",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2edd597-828e-4030-b762-61f93c5cdb7f",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Signed amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "b53faaa2-9907-4f91-b310-c38d130a7760",
            "sourceColumn": "Signed amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Counterparty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1bdbb7f-ffe1-47e4-9339-274566b497ec",
            "sourceColumn": "Counterparty",
            "summarizeBy": "none"
          },
          {
            "name": "Entity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab0d4a10-532a-47b9-a75b-0c188284ced8",
            "sourceColumn": "Entity",
            "summarizeBy": "none"
          },
          {
            "name": "Value date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "195703bf-bc28-43d2-8247-723967aee353",
            "sourceColumn": "Value date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_21c2e1c1-fc5e-48e0-b80c-4d6978561abc"
                },
                "isDefault": true,
                "relationship": "34acc811-31fa-48a7-b0ae-3c78e0cc1dc8"
              }
            ]
          },
          {
            "name": "Maturity date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "bdb74240-bfaf-4933-b54b-cebf1100a2bc",
            "sourceColumn": "Maturity date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2466a5ef-6e87-4d87-b0cc-2785f10759c5"
                },
                "isDefault": true,
                "relationship": "b9da0cd2-ffde-4c34-ab84-7e52f2983d1c"
              }
            ]
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa01fce6-eeb9-42dd-9ef9-64322130958c",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce06cbff-41d1-4de1-b67b-512605b75389",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c45bf247-7866-46cc-b236-cd9d6a1fa37c",
        "partitions": [
          {
            "name": "Exposures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Projects\\PortfolioProjects\\currency-exchange-platform\\powerbi-exports\\fx-compliant.xlsx\"), null, true),",
                "    Data = Source{[Item=\"Exposures\", Kind=\"Sheet\"]}[Data],",
                "    Promoted = Table.PromoteHeaders(Data, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"ID\", Int64.Type}, {\"Amount\", type number}, {\"Signed amount\", type number}, {\"Value date\", type datetime}, {\"Maturity date\", type datetime}})",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Hedges",
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "242ac395-8d42-4c0d-b2e3-53a764ff43db",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Exposure ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "6ed085db-94e7-456e-8b3d-a899439fcc94",
            "sourceColumn": "Exposure ID",
            "summarizeBy": "none"
          },
          {
            "name": "Instrument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6cffc53-456e-4b22-a67a-124905c8f4e7",
            "sourceColumn": "Instrument",
            "summarizeBy": "none"
          },
          {
            "name": "Direction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e8c8301-3b50-40be-8ff6-aedea9f5fea7",
            "sourceColumn": "Direction",
            "summarizeBy": "none"
          },
          {
            "name": "Pair",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a14372e-81a5-4383-9993-7041ed61e4da",
            "sourceColumn": "Pair",
            "summarizeBy": "none"
          },
          {
            "name": "Notional",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "8eb123cb-aa17-43b3-bf8a-050fcbb27431",
            "sourceColumn": "Notional",
            "summarizeBy": "sum"
          },
          {
            "name": "Contract rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "4e738ae9-a2ef-40b2-a475-cad69d695774",
            "sourceColumn": "Contract rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Spot rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "12b6c467-fb7e-4c89-958e-4af10cc9d712",
            "sourceColumn": "Spot rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Mark-to-market",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "a02f269c-0eb9-436e-a616-1d303f61a3ec",
            "sourceColumn": "Mark-to-market",
            "summarizeBy": "sum"
          },
          {
            "name": "Unrealized P&L",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "169ec210-b8da-4ddf-b38b-d2d53965c6e6",
            "sourceColumn": "Unrealized P&L",
            "summarizeBy": "sum"
          },
          {
            "name": "Hedge ratio %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "c02550b0-da0a-4615-88e2-34402e9bc067",
            "sourceColumn": "Hedge ratio %",
            "summarizeBy": "sum"
          },
          {
            "name": "Effectiveness %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "84a3d815-5d58-4009-a3f4-56607ad8ff3c",
            "sourceColumn": "Effectiveness %",
            "summarizeBy": "sum"
          },
          {
            "name": "Effective",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c402ff6-080e-403b-a78a-b72af3c31f29",
            "sourceColumn": "Effective",
            "summarizeBy": "none"
          },
          {
            "name": "Maturity date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "f7d14b02-4c4a-4eb7-9710-6b39a6f9d782",
            "sourceColumn": "Maturity date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6ef7637a-e901-41bf-8f5e-395b71cf5eec"
                },
                "isDefault": true,
                "relationship": "32ffad15-7bdc-4e4e-b22d-70d99822e5e5"
              }
            ]
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce2fe870-9644-4cb8-b1ac-9dd89ff2f331",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Verdict",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "VAR eff = Hedges[Effectiveness %]",
              "RETURN",
              "SWITCH (",
              "    TRUE (),",
              "    ISBLANK ( Hedges[Exposure ID] ), \"Economic\",",
              "    ISBLANK ( eff ), \"N/A\",",
              "    ABS ( eff ) >= 80 && ABS ( eff ) <= 125, \"PASS\",",
              "    \"FAIL\"",
              ")"
            ],
            "lineageTag": "781464d6-338c-4768-b8c5-96d3fe391d89",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "21cd2a24-4b53-4a06-b862-507356bff1c9",
        "measures": [
          {
            "name": "Total Notional",
            "expression": "SUM ( Hedges[Notional] )",
            "formatString": "#,0.00",
            "lineageTag": "8c6dede7-8a88-49c0-b931-13cf02541de1"
          },
          {
            "name": "Total Unrealized P&L",
            "expression": "SUM ( Hedges[Unrealized P&L] )",
            "formatString": "#,0.00",
            "lineageTag": "cbc0348a-d029-4740-a45f-528a04e479e9"
          },
          {
            "name": "Avg Hedge Ratio %",
            "expression": "AVERAGE ( Hedges[Hedge ratio %] )",
            "formatString": "0.00",
            "lineageTag": "e4eefe6b-bfe0-4b50-9b21-8ac48215d09e"
          },
          {
            "name": "Avg Effectiveness %",
            "expression": "AVERAGE ( Hedges[Effectiveness %] )",
            "formatString": "0.00",
            "lineageTag": "82c68f62-0d68-41bc-a81d-331a658a6027"
          },
          {
            "name": "Designated Hedges",
            "expression": "CALCULATE ( COUNTROWS ( Hedges ), NOT ISBLANK ( Hedges[Exposure ID] ) )",
            "formatString": "0",
            "lineageTag": "5db18c00-1fbb-4eb3-bf68-10a73816731c"
          },
          {
            "name": "Assessed Hedges",
            "expression": [
              "CALCULATE (",
              "    COUNTROWS ( Hedges ),",
              "    NOT ISBLANK ( Hedges[Exposure ID] ),",
              "    NOT ISBLANK ( Hedges[Effectiveness %] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1bc3bf09-773f-419c-aae7-3ecbcf9d6bbc"
          },
          {
            "name": "Passing Hedges",
            "expression": [
              "CALCULATE (",
              "    COUNTROWS ( Hedges ),",
              "    FILTER (",
              "        Hedges,",
              "        NOT ISBLANK ( Hedges[Exposure ID] )",
              "            && NOT ISBLANK ( Hedges[Effectiveness %] )",
              "            && ABS ( Hedges[Effectiveness %] ) >= 80",
              "            && ABS ( Hedges[Effectiveness %] ) <= 125",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2e4fd4e1-6a24-4a8d-aca8-e0734dff66ff"
          },
          {
            "name": "Failing Hedges",
            "expression": [
              "CALCULATE (",
              "    COUNTROWS ( Hedges ),",
              "    FILTER (",
              "        Hedges,",
              "        NOT ISBLANK ( Hedges[Exposure ID] )",
              "            && NOT ISBLANK ( Hedges[Effectiveness %] )",
              "            && ( ABS ( Hedges[Effectiveness %] ) < 80 || ABS ( Hedges[Effectiveness %] ) > 125 )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6d0bab45-f438-4a67-9f40-4ef8b77abd24"
          },
          {
            "name": "Not Assessable Hedges",
            "expression": [
              "CALCULATE (",
              "    COUNTROWS ( Hedges ),",
              "    FILTER ( Hedges, NOT ISBLANK ( Hedges[Exposure ID] ) && ISBLANK ( Hedges[Effectiveness %] ) )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7a86efd4-d069-4c6b-a9fa-f33724dbd267"
          },
          {
            "name": "Pass Rate %",
            "expression": "DIVIDE ( [Passing Hedges], [Assessed Hedges] )",
            "formatString": "0.0%",
            "lineageTag": "61de2043-dcd0-4b06-a4f0-a687d36e9f8d"
          },
          {
            "name": "Compliance Status",
            "expression": [
              "VAR assessed = [Assessed Hedges]",
              "VAR fail = [Failing Hedges]",
              "RETURN",
              "SWITCH (",
              "    TRUE (),",
              "    assessed = 0, \"NO ASSESSABLE HEDGES\",",
              "    fail = 0, \"COMPLIANT — all assessed hedges highly effective\",",
              "    \"REVIEW REQUIRED — \" & fail & \" hedge(s) outside the effective band\"",
              ")"
            ],
            "lineageTag": "ea5c9989-e75f-460a-9afb-eab454cb3f5d"
          },
          {
            "name": "Compliance Status Color",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    [Assessed Hedges] = 0, \"#6B7280\",",
              "    [Failing Hedges] = 0, \"#1B7A3D\",",
              "    \"#B02A2A\"",
              ")"
            ],
            "lineageTag": "e634e6d0-978c-4f22-a549-b4aaabf7c373"
          }
        ],
        "partitions": [
          {
            "name": "Hedges",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Projects\\PortfolioProjects\\currency-exchange-platform\\powerbi-exports\\fx-compliant.xlsx\"), null, true),",
                "    Data = Source{[Item=\"Hedges\", Kind=\"Sheet\"]}[Data],",
                "    Promoted = Table.PromoteHeaders(Data, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"ID\", Int64.Type}, {\"Exposure ID\", Int64.Type}, {\"Notional\", type number}, {\"Contract rate\", type number}, {\"Spot rate\", type number}, {\"Mark-to-market\", type number}, {\"Unrealized P&L\", type number}, {\"Hedge ratio %\", type number}, {\"Effectiveness %\", type number}, {\"Maturity date\", type datetime}})",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Rate History",
        "columns": [
          {
            "name": "Pair",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fc9cd11-bce6-4b97-8326-e222d7e934a4",
            "sourceColumn": "Pair",
            "summarizeBy": "none"
          },
          {
            "name": "Captured at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd hh:nn",
            "lineageTag": "c9217038-7a48-42dc-8763-8a9f75a4f22a",
            "sourceColumn": "Captured at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_da8a400a-8ede-4b63-9798-9a361c5655bc"
                },
                "isDefault": true,
                "relationship": "765c8a63-69f5-4a20-b2e4-b9847bf594dd"
              }
            ]
          },
          {
            "name": "Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "5988c816-a7fa-46ff-a863-c2b690e5c9fc",
            "sourceColumn": "Rate",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b565f338-6e22-4aa5-a594-6c1952bd5098",
        "measures": [
          {
            "name": "Latest Rate",
            "expression": "LASTNONBLANKVALUE ( 'Rate History'[Captured at], AVERAGE ( 'Rate History'[Rate] ) )",
            "formatString": "0.0000",
            "lineageTag": "cffd9899-ac3e-443d-b3db-06cb343a51dd"
          },
          {
            "name": "Rate Change %",
            "expression": [
              "VAR firstD = MIN ( 'Rate History'[Captured at] )",
              "VAR lastD = MAX ( 'Rate History'[Captured at] )",
              "VAR firstR = CALCULATE ( AVERAGE ( 'Rate History'[Rate] ), 'Rate History'[Captured at] = firstD )",
              "VAR lastR = CALCULATE ( AVERAGE ( 'Rate History'[Rate] ), 'Rate History'[Captured at] = lastD )",
              "RETURN DIVIDE ( lastR - firstR, firstR )"
            ],
            "formatString": "0.0%",
            "lineageTag": "866b8a15-d4b2-4bcf-9e2b-6b3bbe9dff4a"
          }
        ],
        "partitions": [
          {
            "name": "Rate History",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Projects\\PortfolioProjects\\currency-exchange-platform\\powerbi-exports\\fx-compliant.xlsx\"), null, true),",
                "    Data = Source{[Item=\"Rate History\", Kind=\"Sheet\"]}[Data],",
                "    Promoted = Table.PromoteHeaders(Data, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Pair\", type text}, {\"Captured at\", type datetime}, {\"Rate\", type number}})",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Summary KPIs",
        "columns": [
          {
            "name": "Metric",
            "dataType": "string",
            "lineageTag": "966c89d4-47e8-42a0-8b0a-9f5785b3a24f",
            "sourceColumn": "Metric"
          },
          {
            "name": "Value",
            "dataType": "string",
            "lineageTag": "e2237120-d5ca-4688-8674-181c72b68345",
            "sourceColumn": "Value"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6645743d-acfc-4baa-9ee9-763fbe080ed9",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3983fad-edd2-4b6d-ae69-ef635d4529ee",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cef03b11-565b-4482-98ee-1c22a50c4297",
            "sourceColumn": "Column5",
            "summarizeBy": "none"
          },
          {
            "name": "Column6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56f49343-b4db-4e19-9585-3123a323910d",
            "sourceColumn": "Column6",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a673905e-6f7e-4ba8-b5c2-2adb15da73f8",
        "partitions": [
          {
            "name": "Summary KPIs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Projects\\PortfolioProjects\\currency-exchange-platform\\powerbi-exports\\fx-compliant.xlsx\"), null, true),",
                "    Data = Source{[Item=\"Portfolio Summary\", Kind=\"Sheet\"]}[Data],",
                "    NoBlanks = Table.SelectRows(Data, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {null, \"\"}))),",
                "    Kept = Table.FirstN(NoBlanks, 3),",
                "    Renamed = Table.RenameColumns(Kept, {{\"Column1\", \"Metric\"}, {\"Column2\", \"Value\"}}),",
                "    Typed = Table.TransformColumnTypes(Renamed, {{\"Metric\", type text}, {\"Value\", type text}})",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_b7d72455-25ed-43f4-9400-86a0add8e087",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ab22e49e-7a08-4af7-b472-9f7519008116",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "658ccdd7-ed27-4496-86b0-0901df61f04e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9f579ed9-47ed-4efa-8a21-4aee9d903c41",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e6087bed-66ff-4075-b49e-69affaaf8d07",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "37563b3f-3343-42d2-bf0a-a2bdc77e3384",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "46ccfb6a-3569-4062-b4ff-5f79a2a22b07",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "66a3662d-d0f6-4d07-ac0e-96b90bb11b16",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a151df4e-0b5d-4056-a865-13d3b19c43e5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1ad26a4d-b59a-4f80-ab4d-89de2052d27b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1e2c7dfe-55c5-4391-83e7-c4ae3f0def15",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "88caee98-bcb1-4691-9669-9fb1cce778ff",
                "ordinal": 3
              }
            ],
            "lineageTag": "8e964fa7-5f02-4063-a9f2-0dd66c7a9abc"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e01e3073-4b6b-48b7-b3f2-961dbc9d8162",
        "partitions": [
          {
            "name": "DateTableTemplate_b7d72455-25ed-43f4-9400-86a0add8e087",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_21c2e1c1-fc5e-48e0-b80c-4d6978561abc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "37f57275-0ecc-4615-9372-1e6d7827dc21",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c97ef549-5c67-404d-bbb2-241b381b0bf3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "519d4a38-1e81-4911-8760-73893a89f8d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4bd07f56-c21c-425a-a110-ae30a39bcdbc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1d002432-70ed-4ea3-9ffa-c027f933ecd1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f4e6a07e-a9a6-4df5-9587-824596fdf076",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b4233229-6118-4a03-a2c0-95755b5a7855",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ddbcd3ad-630a-44c1-9c1f-2fa1e8d9ba63",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6178e7b9-4592-471f-b11f-c0ba926d6784",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "93276777-2425-464d-ba2f-2a04a0052239",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d4af9ddb-db7b-47d6-90c5-c213dd8bf0bb",
                "ordinal": 3
              }
            ],
            "lineageTag": "4516fbef-c96b-4669-8df2-c9f73ce1a7e3"
          }
        ],
        "isHidden": true,
        "lineageTag": "bf4671f5-c073-48a6-a8fd-0e7be9df519b",
        "partitions": [
          {
            "name": "LocalDateTable_21c2e1c1-fc5e-48e0-b80c-4d6978561abc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Exposures'[Value date])), 1, 1), Date(Year(MAX('Exposures'[Value date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2466a5ef-6e87-4d87-b0cc-2785f10759c5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2f2f8765-1cab-4ec3-a3c8-678326514148",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0385ba4a-765f-4bac-bf0f-195585743200",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "92897291-7689-4386-90d0-7a2df0a66884",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7ef2cbe2-9697-4ee1-94e3-4b844b94c5f5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7b9307cc-0bf2-4740-a647-6d583f6cce39",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "22d6a955-d548-4257-847b-2e9cec022727",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d8c3c5a7-4d5f-4eec-b58d-1a60046d73a1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "13873807-e9ee-4b7a-b76d-d3780f70ea0f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c417283f-f36b-4c72-a711-1083237218c7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f6022a3c-93db-49af-b34f-b8abbd2b3263",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "bf435fb2-41b8-423f-a78a-3d756f27a8d0",
                "ordinal": 3
              }
            ],
            "lineageTag": "fd8303a4-098f-467e-a38c-2e477da91ae4"
          }
        ],
        "isHidden": true,
        "lineageTag": "19303938-0508-4567-bd7f-4b4290ab6f0f",
        "partitions": [
          {
            "name": "LocalDateTable_2466a5ef-6e87-4d87-b0cc-2785f10759c5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Exposures'[Maturity date])), 1, 1), Date(Year(MAX('Exposures'[Maturity date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_6ef7637a-e901-41bf-8f5e-395b71cf5eec",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5e3a0810-90b6-481d-bae3-1dc46319f48f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1ce1c7e1-6d2a-487f-a3fb-3ab15caf48ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "49af78ec-b0d5-48e4-9028-bc2f95f8cc4c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cd6a6a35-0dab-440d-891e-46bfba9d8015",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d2593fed-747e-4890-8294-a6e1a33e57e2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f381ed05-3228-4843-a426-cabcb6833f45",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3df75504-5d80-42cb-80dd-1b9e2ea77917",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3e380517-d1cb-4eb6-951f-62122b46b608",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2512904f-77a4-4534-abf0-0ac9ea3198a8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "efd1277b-4aab-4dea-a12f-617ac228d551",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "66ef5764-38c3-41d9-ae3b-b4b1e6032fc3",
                "ordinal": 3
              }
            ],
            "lineageTag": "e2b401d6-ba63-43cd-adca-d4e6da98f53f"
          }
        ],
        "isHidden": true,
        "lineageTag": "90e3bb37-9066-4411-ae81-e16a960472c7",
        "partitions": [
          {
            "name": "LocalDateTable_6ef7637a-e901-41bf-8f5e-395b71cf5eec",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Hedges'[Maturity date])), 1, 1), Date(Year(MAX('Hedges'[Maturity date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_da8a400a-8ede-4b63-9798-9a361c5655bc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cb40d2ef-158b-4656-b474-edc01f094a7b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "83b18585-4fb0-4579-8c75-52c9143f8a7e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7ea948c1-38dd-4c94-b100-560ec991c586",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "aff5ed5d-125c-4c82-97f0-549803f8c0fc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e97345d2-60af-4ca2-ab73-c3e1fd5b1378",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c2b53339-2aa7-48b4-9962-b20b79384903",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8d6c681-9f7c-444a-ab40-af55d37d5ef4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3c36a02a-a79f-44a6-9da9-5924f14d6ecf",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "360fc85e-c34b-4f34-9deb-54dc41fcc88f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bf88f173-8763-4cb8-806f-c136e3fde993",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ca736e39-51d2-4a0f-b93a-55e538ce39f8",
                "ordinal": 3
              }
            ],
            "lineageTag": "e2baf4da-1181-449d-bad1-d6344bef78fe"
          }
        ],
        "isHidden": true,
        "lineageTag": "297c6bec-c1f0-45f0-baa1-ef8717a0143e",
        "partitions": [
          {
            "name": "LocalDateTable_da8a400a-8ede-4b63-9798-9a361c5655bc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Rate History'[Captured at])), 1, 1), Date(Year(MAX('Rate History'[Captured at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}